/*
Copyright 2020 Google LLC

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//+build !wireinject

package handler

import (
	"cloud.google.com/go/pubsub"
	"context"
	"github.com/google/knative-gcp/pkg/broker/config"
	"github.com/google/knative-gcp/pkg/metrics"
)

// Injectors from wire.go:

func InitializeTestFanoutPool(ctx context.Context, podName metrics.PodName, containerName metrics.ContainerName, targets config.ReadonlyTargets, pubsubClient *pubsub.Client, opts ...Option) (*FanoutPool, error) {
	client := _wireClientValue
	v := _wireValue
	retryClient, err := NewRetryClient(ctx, pubsubClient, v...)
	if err != nil {
		return nil, err
	}
	deliveryReporter, err := metrics.NewDeliveryReporter(podName, containerName)
	if err != nil {
		return nil, err
	}
	fanoutPool, err := NewFanoutPool(targets, pubsubClient, client, retryClient, deliveryReporter, opts...)
	if err != nil {
		return nil, err
	}
	return fanoutPool, nil
}

var (
	_wireClientValue = DefaultHTTPClient
	_wireValue       = DefaultCEClientOpts
)

func InitializeTestRetryPool(targets config.ReadonlyTargets, podName metrics.PodName, containerName metrics.ContainerName, pubsubClient *pubsub.Client, opts ...Option) (*RetryPool, error) {
	client := _wireHttpClientValue
	deliveryReporter, err := metrics.NewDeliveryReporter(podName, containerName)
	if err != nil {
		return nil, err
	}
	retryPool, err := NewRetryPool(targets, pubsubClient, client, deliveryReporter, opts...)
	if err != nil {
		return nil, err
	}
	return retryPool, nil
}

var (
	_wireHttpClientValue = DefaultHTTPClient
)
