{
 "title": "Knative with GCP",
 "description": "Knative with GCP",
 "time": { "from": "now-120m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Broker Dispatch Time",
   "type": "heatmap",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "histogram_quantile(0.98, rate(broker_dispatch_time_bucket[1m]))",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Trigger Dispatch Time",
   "type": "heatmap",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "histogram_quantile(0.98, rate(trigger_dispatch_time_bucket[1m]))",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Trigger Filter Time",
   "type": "heatmap",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "histogram_quantile(0.98, rate(trigger_filter_time_bucket[1m]))",
     "legendFormat": "{{le}}"
    }
   ]
  }
 ]
}