// +build !ignore_autogenerated

/*
Copyright 2020 Google LLC

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by deepcopy-gen. DO NOT EDIT.

package v1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CloudStorageSource) DeepCopyInto(out *CloudStorageSource) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CloudStorageSource.
func (in *CloudStorageSource) DeepCopy() *CloudStorageSource {
	if in == nil {
		return nil
	}
	out := new(CloudStorageSource)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *CloudStorageSource) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CloudStorageSourceList) DeepCopyInto(out *CloudStorageSourceList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]CloudStorageSource, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CloudStorageSourceList.
func (in *CloudStorageSourceList) DeepCopy() *CloudStorageSourceList {
	if in == nil {
		return nil
	}
	out := new(CloudStorageSourceList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *CloudStorageSourceList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CloudStorageSourceSpec) DeepCopyInto(out *CloudStorageSourceSpec) {
	*out = *in
	in.PubSubSpec.DeepCopyInto(&out.PubSubSpec)
	if in.EventTypes != nil {
		in, out := &in.EventTypes, &out.EventTypes
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CloudStorageSourceSpec.
func (in *CloudStorageSourceSpec) DeepCopy() *CloudStorageSourceSpec {
	if in == nil {
		return nil
	}
	out := new(CloudStorageSourceSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CloudStorageSourceStatus) DeepCopyInto(out *CloudStorageSourceStatus) {
	*out = *in
	in.PubSubStatus.DeepCopyInto(&out.PubSubStatus)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CloudStorageSourceStatus.
func (in *CloudStorageSourceStatus) DeepCopy() *CloudStorageSourceStatus {
	if in == nil {
		return nil
	}
	out := new(CloudStorageSourceStatus)
	in.DeepCopyInto(out)
	return out
}
