/*
Copyright 2020 Google LLC.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

package testloggingutil

const (
	// LoggingE2ETestAnnotation is the annotation used by the TestCloudLogging E2E tests to verify
	// that the knative-gcp Controller and Webhook write to Cloud Logging. Essentially, if a Topic
	// has this annotation, then the value of this annotation is written into the logs (the value
	// is expected to be a UUID generated by the test).
	LoggingE2ETestAnnotation = "events.cloud.google.com/e2eLoggingTest"

	// LoggingE2ETestEnvVarName is the name of the environment variable used to send containers a
	// string for them to log. This is used in the TestCloudLogging E2E tests to verify logs are
	// showing up in Cloud Logging.
	LoggingE2ETestEnvVarName = "E2E_LOGGING_TEST"

	// LoggingE2EFieldName is the name of the JSON field that includes the value of the annotation.
	// Used in the TestCloudLogging E2E tests to verify logs are showing up in Cloud Logging.
	LoggingE2EFieldName = "e2eLoggingTestField"
)
