// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//+build !wireinject

package main

import (
	"context"
	"github.com/google/knative-gcp/pkg/broker/config/volume"
	"github.com/google/knative-gcp/pkg/broker/handler/pool"
)

// Injectors from wire.go:

func InitializeSyncPool(ctx context.Context, projectID pool.ProjectID, targetsVolumeOpts []volume.Option, opts ...pool.Option) (*pool.RetryPool, error) {
	readonlyTargets, err := volume.NewTargetsFromFile(targetsVolumeOpts...)
	if err != nil {
		return nil, err
	}
	client, err := pool.NewPubsubClient(ctx, projectID)
	if err != nil {
		return nil, err
	}
	httpClient := _wireClientValue
	retryPool, err := pool.NewRetryPool(readonlyTargets, client, httpClient, opts...)
	if err != nil {
		return nil, err
	}
	return retryPool, nil
}

var (
	_wireClientValue = pool.DefaultHTTPClient
)
