/*
Copyright 2019 Google LLC

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by lister-gen. DO NOT EDIT.

package v1alpha1

import (
	v1alpha1 "github.com/GoogleCloudPlatform/cloud-run-events/pkg/apis/events/v1alpha1"
	"k8s.io/apimachinery/pkg/api/errors"
	"k8s.io/apimachinery/pkg/labels"
	"k8s.io/client-go/tools/cache"
)

// PubSubChannelLister helps list PubSubChannels.
type PubSubChannelLister interface {
	// List lists all PubSubChannels in the indexer.
	List(selector labels.Selector) (ret []*v1alpha1.PubSubChannel, err error)
	// PubSubChannels returns an object that can list and get PubSubChannels.
	PubSubChannels(namespace string) PubSubChannelNamespaceLister
	PubSubChannelListerExpansion
}

// pubSubChannelLister implements the PubSubChannelLister interface.
type pubSubChannelLister struct {
	indexer cache.Indexer
}

// NewPubSubChannelLister returns a new PubSubChannelLister.
func NewPubSubChannelLister(indexer cache.Indexer) PubSubChannelLister {
	return &pubSubChannelLister{indexer: indexer}
}

// List lists all PubSubChannels in the indexer.
func (s *pubSubChannelLister) List(selector labels.Selector) (ret []*v1alpha1.PubSubChannel, err error) {
	err = cache.ListAll(s.indexer, selector, func(m interface{}) {
		ret = append(ret, m.(*v1alpha1.PubSubChannel))
	})
	return ret, err
}

// PubSubChannels returns an object that can list and get PubSubChannels.
func (s *pubSubChannelLister) PubSubChannels(namespace string) PubSubChannelNamespaceLister {
	return pubSubChannelNamespaceLister{indexer: s.indexer, namespace: namespace}
}

// PubSubChannelNamespaceLister helps list and get PubSubChannels.
type PubSubChannelNamespaceLister interface {
	// List lists all PubSubChannels in the indexer for a given namespace.
	List(selector labels.Selector) (ret []*v1alpha1.PubSubChannel, err error)
	// Get retrieves the PubSubChannel from the indexer for a given namespace and name.
	Get(name string) (*v1alpha1.PubSubChannel, error)
	PubSubChannelNamespaceListerExpansion
}

// pubSubChannelNamespaceLister implements the PubSubChannelNamespaceLister
// interface.
type pubSubChannelNamespaceLister struct {
	indexer   cache.Indexer
	namespace string
}

// List lists all PubSubChannels in the indexer for a given namespace.
func (s pubSubChannelNamespaceLister) List(selector labels.Selector) (ret []*v1alpha1.PubSubChannel, err error) {
	err = cache.ListAllByNamespace(s.indexer, s.namespace, selector, func(m interface{}) {
		ret = append(ret, m.(*v1alpha1.PubSubChannel))
	})
	return ret, err
}

// Get retrieves the PubSubChannel from the indexer for a given namespace and name.
func (s pubSubChannelNamespaceLister) Get(name string) (*v1alpha1.PubSubChannel, error) {
	obj, exists, err := s.indexer.GetByKey(s.namespace + "/" + name)
	if err != nil {
		return nil, err
	}
	if !exists {
		return nil, errors.NewNotFound(v1alpha1.Resource("pubsubchannel"), name)
	}
	return obj.(*v1alpha1.PubSubChannel), nil
}
