/*
Copyright 2020 Google LLC

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	"time"

	v1alpha1 "github.com/google/knative-gcp/pkg/apis/events/v1alpha1"
	scheme "github.com/google/knative-gcp/pkg/client/clientset/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// CloudAuditLogsSourcesGetter has a method to return a CloudAuditLogsSourceInterface.
// A group's client should implement this interface.
type CloudAuditLogsSourcesGetter interface {
	CloudAuditLogsSources(namespace string) CloudAuditLogsSourceInterface
}

// CloudAuditLogsSourceInterface has methods to work with CloudAuditLogsSource resources.
type CloudAuditLogsSourceInterface interface {
	Create(*v1alpha1.CloudAuditLogsSource) (*v1alpha1.CloudAuditLogsSource, error)
	Update(*v1alpha1.CloudAuditLogsSource) (*v1alpha1.CloudAuditLogsSource, error)
	UpdateStatus(*v1alpha1.CloudAuditLogsSource) (*v1alpha1.CloudAuditLogsSource, error)
	Delete(name string, options *v1.DeleteOptions) error
	DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error
	Get(name string, options v1.GetOptions) (*v1alpha1.CloudAuditLogsSource, error)
	List(opts v1.ListOptions) (*v1alpha1.CloudAuditLogsSourceList, error)
	Watch(opts v1.ListOptions) (watch.Interface, error)
	Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha1.CloudAuditLogsSource, err error)
	CloudAuditLogsSourceExpansion
}

// cloudAuditLogsSources implements CloudAuditLogsSourceInterface
type cloudAuditLogsSources struct {
	client rest.Interface
	ns     string
}

// newCloudAuditLogsSources returns a CloudAuditLogsSources
func newCloudAuditLogsSources(c *EventsV1alpha1Client, namespace string) *cloudAuditLogsSources {
	return &cloudAuditLogsSources{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the cloudAuditLogsSource, and returns the corresponding cloudAuditLogsSource object, and an error if there is any.
func (c *cloudAuditLogsSources) Get(name string, options v1.GetOptions) (result *v1alpha1.CloudAuditLogsSource, err error) {
	result = &v1alpha1.CloudAuditLogsSource{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("cloudauditlogssources").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do().
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of CloudAuditLogsSources that match those selectors.
func (c *cloudAuditLogsSources) List(opts v1.ListOptions) (result *v1alpha1.CloudAuditLogsSourceList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v1alpha1.CloudAuditLogsSourceList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("cloudauditlogssources").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do().
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested cloudAuditLogsSources.
func (c *cloudAuditLogsSources) Watch(opts v1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("cloudauditlogssources").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch()
}

// Create takes the representation of a cloudAuditLogsSource and creates it.  Returns the server's representation of the cloudAuditLogsSource, and an error, if there is any.
func (c *cloudAuditLogsSources) Create(cloudAuditLogsSource *v1alpha1.CloudAuditLogsSource) (result *v1alpha1.CloudAuditLogsSource, err error) {
	result = &v1alpha1.CloudAuditLogsSource{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("cloudauditlogssources").
		Body(cloudAuditLogsSource).
		Do().
		Into(result)
	return
}

// Update takes the representation of a cloudAuditLogsSource and updates it. Returns the server's representation of the cloudAuditLogsSource, and an error, if there is any.
func (c *cloudAuditLogsSources) Update(cloudAuditLogsSource *v1alpha1.CloudAuditLogsSource) (result *v1alpha1.CloudAuditLogsSource, err error) {
	result = &v1alpha1.CloudAuditLogsSource{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("cloudauditlogssources").
		Name(cloudAuditLogsSource.Name).
		Body(cloudAuditLogsSource).
		Do().
		Into(result)
	return
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().

func (c *cloudAuditLogsSources) UpdateStatus(cloudAuditLogsSource *v1alpha1.CloudAuditLogsSource) (result *v1alpha1.CloudAuditLogsSource, err error) {
	result = &v1alpha1.CloudAuditLogsSource{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("cloudauditlogssources").
		Name(cloudAuditLogsSource.Name).
		SubResource("status").
		Body(cloudAuditLogsSource).
		Do().
		Into(result)
	return
}

// Delete takes name of the cloudAuditLogsSource and deletes it. Returns an error if one occurs.
func (c *cloudAuditLogsSources) Delete(name string, options *v1.DeleteOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("cloudauditlogssources").
		Name(name).
		Body(options).
		Do().
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *cloudAuditLogsSources) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	var timeout time.Duration
	if listOptions.TimeoutSeconds != nil {
		timeout = time.Duration(*listOptions.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Namespace(c.ns).
		Resource("cloudauditlogssources").
		VersionedParams(&listOptions, scheme.ParameterCodec).
		Timeout(timeout).
		Body(options).
		Do().
		Error()
}

// Patch applies the patch and returns the patched cloudAuditLogsSource.
func (c *cloudAuditLogsSources) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha1.CloudAuditLogsSource, err error) {
	result = &v1alpha1.CloudAuditLogsSource{}
	err = c.client.Patch(pt).
		Namespace(c.ns).
		Resource("cloudauditlogssources").
		SubResource(subresources...).
		Name(name).
		Body(data).
		Do().
		Into(result)
	return
}
