/*
Copyright 2019 Google LLC

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	v1alpha1 "github.com/google/knative-gcp/pkg/apis/events/v1alpha1"
	scheme "github.com/google/knative-gcp/pkg/client/clientset/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// PubSubsGetter has a method to return a PubSubInterface.
// A group's client should implement this interface.
type PubSubsGetter interface {
	PubSubs(namespace string) PubSubInterface
}

// PubSubInterface has methods to work with PubSub resources.
type PubSubInterface interface {
	Create(*v1alpha1.PubSub) (*v1alpha1.PubSub, error)
	Update(*v1alpha1.PubSub) (*v1alpha1.PubSub, error)
	UpdateStatus(*v1alpha1.PubSub) (*v1alpha1.PubSub, error)
	Delete(name string, options *v1.DeleteOptions) error
	DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error
	Get(name string, options v1.GetOptions) (*v1alpha1.PubSub, error)
	List(opts v1.ListOptions) (*v1alpha1.PubSubList, error)
	Watch(opts v1.ListOptions) (watch.Interface, error)
	Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha1.PubSub, err error)
	PubSubExpansion
}

// pubSubs implements PubSubInterface
type pubSubs struct {
	client rest.Interface
	ns     string
}

// newPubSubs returns a PubSubs
func newPubSubs(c *EventsV1alpha1Client, namespace string) *pubSubs {
	return &pubSubs{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the pubSub, and returns the corresponding pubSub object, and an error if there is any.
func (c *pubSubs) Get(name string, options v1.GetOptions) (result *v1alpha1.PubSub, err error) {
	result = &v1alpha1.PubSub{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("pubsubs").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do().
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of PubSubs that match those selectors.
func (c *pubSubs) List(opts v1.ListOptions) (result *v1alpha1.PubSubList, err error) {
	result = &v1alpha1.PubSubList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("pubsubs").
		VersionedParams(&opts, scheme.ParameterCodec).
		Do().
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested pubSubs.
func (c *pubSubs) Watch(opts v1.ListOptions) (watch.Interface, error) {
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("pubsubs").
		VersionedParams(&opts, scheme.ParameterCodec).
		Watch()
}

// Create takes the representation of a pubSub and creates it.  Returns the server's representation of the pubSub, and an error, if there is any.
func (c *pubSubs) Create(pubSub *v1alpha1.PubSub) (result *v1alpha1.PubSub, err error) {
	result = &v1alpha1.PubSub{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("pubsubs").
		Body(pubSub).
		Do().
		Into(result)
	return
}

// Update takes the representation of a pubSub and updates it. Returns the server's representation of the pubSub, and an error, if there is any.
func (c *pubSubs) Update(pubSub *v1alpha1.PubSub) (result *v1alpha1.PubSub, err error) {
	result = &v1alpha1.PubSub{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("pubsubs").
		Name(pubSub.Name).
		Body(pubSub).
		Do().
		Into(result)
	return
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().

func (c *pubSubs) UpdateStatus(pubSub *v1alpha1.PubSub) (result *v1alpha1.PubSub, err error) {
	result = &v1alpha1.PubSub{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("pubsubs").
		Name(pubSub.Name).
		SubResource("status").
		Body(pubSub).
		Do().
		Into(result)
	return
}

// Delete takes name of the pubSub and deletes it. Returns an error if one occurs.
func (c *pubSubs) Delete(name string, options *v1.DeleteOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("pubsubs").
		Name(name).
		Body(options).
		Do().
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *pubSubs) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("pubsubs").
		VersionedParams(&listOptions, scheme.ParameterCodec).
		Body(options).
		Do().
		Error()
}

// Patch applies the patch and returns the patched pubSub.
func (c *pubSubs) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha1.PubSub, err error) {
	result = &v1alpha1.PubSub{}
	err = c.client.Patch(pt).
		Namespace(c.ns).
		Resource("pubsubs").
		SubResource(subresources...).
		Name(name).
		Body(data).
		Do().
		Into(result)
	return
}
