/*
Copyright 2019 Google LLC

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	v1alpha1 "github.com/GoogleCloudPlatform/cloud-run-events/pkg/apis/events/v1alpha1"
	scheme "github.com/GoogleCloudPlatform/cloud-run-events/pkg/client/clientset/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// PubSubChannelsGetter has a method to return a PubSubChannelInterface.
// A group's client should implement this interface.
type PubSubChannelsGetter interface {
	PubSubChannels(namespace string) PubSubChannelInterface
}

// PubSubChannelInterface has methods to work with PubSubChannel resources.
type PubSubChannelInterface interface {
	Create(*v1alpha1.PubSubChannel) (*v1alpha1.PubSubChannel, error)
	Update(*v1alpha1.PubSubChannel) (*v1alpha1.PubSubChannel, error)
	UpdateStatus(*v1alpha1.PubSubChannel) (*v1alpha1.PubSubChannel, error)
	Delete(name string, options *v1.DeleteOptions) error
	DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error
	Get(name string, options v1.GetOptions) (*v1alpha1.PubSubChannel, error)
	List(opts v1.ListOptions) (*v1alpha1.PubSubChannelList, error)
	Watch(opts v1.ListOptions) (watch.Interface, error)
	Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha1.PubSubChannel, err error)
	PubSubChannelExpansion
}

// pubSubChannels implements PubSubChannelInterface
type pubSubChannels struct {
	client rest.Interface
	ns     string
}

// newPubSubChannels returns a PubSubChannels
func newPubSubChannels(c *EventsV1alpha1Client, namespace string) *pubSubChannels {
	return &pubSubChannels{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the pubSubChannel, and returns the corresponding pubSubChannel object, and an error if there is any.
func (c *pubSubChannels) Get(name string, options v1.GetOptions) (result *v1alpha1.PubSubChannel, err error) {
	result = &v1alpha1.PubSubChannel{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("pubsubchannels").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do().
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of PubSubChannels that match those selectors.
func (c *pubSubChannels) List(opts v1.ListOptions) (result *v1alpha1.PubSubChannelList, err error) {
	result = &v1alpha1.PubSubChannelList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("pubsubchannels").
		VersionedParams(&opts, scheme.ParameterCodec).
		Do().
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested pubSubChannels.
func (c *pubSubChannels) Watch(opts v1.ListOptions) (watch.Interface, error) {
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("pubsubchannels").
		VersionedParams(&opts, scheme.ParameterCodec).
		Watch()
}

// Create takes the representation of a pubSubChannel and creates it.  Returns the server's representation of the pubSubChannel, and an error, if there is any.
func (c *pubSubChannels) Create(pubSubChannel *v1alpha1.PubSubChannel) (result *v1alpha1.PubSubChannel, err error) {
	result = &v1alpha1.PubSubChannel{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("pubsubchannels").
		Body(pubSubChannel).
		Do().
		Into(result)
	return
}

// Update takes the representation of a pubSubChannel and updates it. Returns the server's representation of the pubSubChannel, and an error, if there is any.
func (c *pubSubChannels) Update(pubSubChannel *v1alpha1.PubSubChannel) (result *v1alpha1.PubSubChannel, err error) {
	result = &v1alpha1.PubSubChannel{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("pubsubchannels").
		Name(pubSubChannel.Name).
		Body(pubSubChannel).
		Do().
		Into(result)
	return
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().

func (c *pubSubChannels) UpdateStatus(pubSubChannel *v1alpha1.PubSubChannel) (result *v1alpha1.PubSubChannel, err error) {
	result = &v1alpha1.PubSubChannel{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("pubsubchannels").
		Name(pubSubChannel.Name).
		SubResource("status").
		Body(pubSubChannel).
		Do().
		Into(result)
	return
}

// Delete takes name of the pubSubChannel and deletes it. Returns an error if one occurs.
func (c *pubSubChannels) Delete(name string, options *v1.DeleteOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("pubsubchannels").
		Name(name).
		Body(options).
		Do().
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *pubSubChannels) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("pubsubchannels").
		VersionedParams(&listOptions, scheme.ParameterCodec).
		Body(options).
		Do().
		Error()
}

// Patch applies the patch and returns the patched pubSubChannel.
func (c *pubSubChannels) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha1.PubSubChannel, err error) {
	result = &v1alpha1.PubSubChannel{}
	err = c.client.Patch(pt).
		Namespace(c.ns).
		Resource("pubsubchannels").
		SubResource(subresources...).
		Name(name).
		Body(data).
		Do().
		Into(result)
	return
}
