// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//+build !wireinject

package main

import (
	"context"
	"github.com/google/knative-gcp/pkg/broker/config/volume"
	"github.com/google/knative-gcp/pkg/broker/ingress"
)

// Injectors from wire.go:

func InitializeHandler(ctx context.Context, args ingress.Args) (*ingress.Handler, error) {
	httpMessageReceiver := ingress.NewHTTPMessageReceiver(args)
	v := _wireValue
	readonlyTargets, err := volume.NewTargetsFromFile(v...)
	if err != nil {
		return nil, err
	}
	client, err := ingress.NewPubsubClient(ctx, args)
	if err != nil {
		return nil, err
	}
	clientClient, err := ingress.NewPubsubDecoupleClient(ctx, client)
	if err != nil {
		return nil, err
	}
	multiTopicDecoupleSink := ingress.NewMultiTopicDecoupleSink(ctx, readonlyTargets, clientClient)
	statsReporter := ingress.NewStatsReporter(args)
	handler := ingress.NewHandler(ctx, httpMessageReceiver, multiTopicDecoupleSink, statsReporter)
	return handler, nil
}

var (
	_wireValue = []volume.Option(nil)
)
