/*
Copyright 2020 Google LLC

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	"time"

	v1alpha1 "github.com/google/knative-gcp/pkg/apis/policy/v1alpha1"
	scheme "github.com/google/knative-gcp/pkg/client/clientset/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// HTTPPoliciesGetter has a method to return a HTTPPolicyInterface.
// A group's client should implement this interface.
type HTTPPoliciesGetter interface {
	HTTPPolicies(namespace string) HTTPPolicyInterface
}

// HTTPPolicyInterface has methods to work with HTTPPolicy resources.
type HTTPPolicyInterface interface {
	Create(*v1alpha1.HTTPPolicy) (*v1alpha1.HTTPPolicy, error)
	Update(*v1alpha1.HTTPPolicy) (*v1alpha1.HTTPPolicy, error)
	Delete(name string, options *v1.DeleteOptions) error
	DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error
	Get(name string, options v1.GetOptions) (*v1alpha1.HTTPPolicy, error)
	List(opts v1.ListOptions) (*v1alpha1.HTTPPolicyList, error)
	Watch(opts v1.ListOptions) (watch.Interface, error)
	Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha1.HTTPPolicy, err error)
	HTTPPolicyExpansion
}

// hTTPPolicies implements HTTPPolicyInterface
type hTTPPolicies struct {
	client rest.Interface
	ns     string
}

// newHTTPPolicies returns a HTTPPolicies
func newHTTPPolicies(c *PolicyV1alpha1Client, namespace string) *hTTPPolicies {
	return &hTTPPolicies{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the hTTPPolicy, and returns the corresponding hTTPPolicy object, and an error if there is any.
func (c *hTTPPolicies) Get(name string, options v1.GetOptions) (result *v1alpha1.HTTPPolicy, err error) {
	result = &v1alpha1.HTTPPolicy{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("httppolicies").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do().
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of HTTPPolicies that match those selectors.
func (c *hTTPPolicies) List(opts v1.ListOptions) (result *v1alpha1.HTTPPolicyList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v1alpha1.HTTPPolicyList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("httppolicies").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do().
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested hTTPPolicies.
func (c *hTTPPolicies) Watch(opts v1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("httppolicies").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch()
}

// Create takes the representation of a hTTPPolicy and creates it.  Returns the server's representation of the hTTPPolicy, and an error, if there is any.
func (c *hTTPPolicies) Create(hTTPPolicy *v1alpha1.HTTPPolicy) (result *v1alpha1.HTTPPolicy, err error) {
	result = &v1alpha1.HTTPPolicy{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("httppolicies").
		Body(hTTPPolicy).
		Do().
		Into(result)
	return
}

// Update takes the representation of a hTTPPolicy and updates it. Returns the server's representation of the hTTPPolicy, and an error, if there is any.
func (c *hTTPPolicies) Update(hTTPPolicy *v1alpha1.HTTPPolicy) (result *v1alpha1.HTTPPolicy, err error) {
	result = &v1alpha1.HTTPPolicy{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("httppolicies").
		Name(hTTPPolicy.Name).
		Body(hTTPPolicy).
		Do().
		Into(result)
	return
}

// Delete takes name of the hTTPPolicy and deletes it. Returns an error if one occurs.
func (c *hTTPPolicies) Delete(name string, options *v1.DeleteOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("httppolicies").
		Name(name).
		Body(options).
		Do().
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *hTTPPolicies) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	var timeout time.Duration
	if listOptions.TimeoutSeconds != nil {
		timeout = time.Duration(*listOptions.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Namespace(c.ns).
		Resource("httppolicies").
		VersionedParams(&listOptions, scheme.ParameterCodec).
		Timeout(timeout).
		Body(options).
		Do().
		Error()
}

// Patch applies the patch and returns the patched hTTPPolicy.
func (c *hTTPPolicies) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha1.HTTPPolicy, err error) {
	result = &v1alpha1.HTTPPolicy{}
	err = c.client.Patch(pt).
		Namespace(c.ns).
		Resource("httppolicies").
		SubResource(subresources...).
		Name(name).
		Body(data).
		Do().
		Into(result)
	return
}
