/*
Copyright 2020 Google LLC

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	"time"

	v1alpha1 "github.com/google/knative-gcp/pkg/apis/policy/v1alpha1"
	scheme "github.com/google/knative-gcp/pkg/client/clientset/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// HTTPPolicyBindingsGetter has a method to return a HTTPPolicyBindingInterface.
// A group's client should implement this interface.
type HTTPPolicyBindingsGetter interface {
	HTTPPolicyBindings(namespace string) HTTPPolicyBindingInterface
}

// HTTPPolicyBindingInterface has methods to work with HTTPPolicyBinding resources.
type HTTPPolicyBindingInterface interface {
	Create(*v1alpha1.HTTPPolicyBinding) (*v1alpha1.HTTPPolicyBinding, error)
	Update(*v1alpha1.HTTPPolicyBinding) (*v1alpha1.HTTPPolicyBinding, error)
	UpdateStatus(*v1alpha1.HTTPPolicyBinding) (*v1alpha1.HTTPPolicyBinding, error)
	Delete(name string, options *v1.DeleteOptions) error
	DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error
	Get(name string, options v1.GetOptions) (*v1alpha1.HTTPPolicyBinding, error)
	List(opts v1.ListOptions) (*v1alpha1.HTTPPolicyBindingList, error)
	Watch(opts v1.ListOptions) (watch.Interface, error)
	Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha1.HTTPPolicyBinding, err error)
	HTTPPolicyBindingExpansion
}

// hTTPPolicyBindings implements HTTPPolicyBindingInterface
type hTTPPolicyBindings struct {
	client rest.Interface
	ns     string
}

// newHTTPPolicyBindings returns a HTTPPolicyBindings
func newHTTPPolicyBindings(c *PolicyV1alpha1Client, namespace string) *hTTPPolicyBindings {
	return &hTTPPolicyBindings{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the hTTPPolicyBinding, and returns the corresponding hTTPPolicyBinding object, and an error if there is any.
func (c *hTTPPolicyBindings) Get(name string, options v1.GetOptions) (result *v1alpha1.HTTPPolicyBinding, err error) {
	result = &v1alpha1.HTTPPolicyBinding{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("httppolicybindings").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do().
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of HTTPPolicyBindings that match those selectors.
func (c *hTTPPolicyBindings) List(opts v1.ListOptions) (result *v1alpha1.HTTPPolicyBindingList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v1alpha1.HTTPPolicyBindingList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("httppolicybindings").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do().
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested hTTPPolicyBindings.
func (c *hTTPPolicyBindings) Watch(opts v1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("httppolicybindings").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch()
}

// Create takes the representation of a hTTPPolicyBinding and creates it.  Returns the server's representation of the hTTPPolicyBinding, and an error, if there is any.
func (c *hTTPPolicyBindings) Create(hTTPPolicyBinding *v1alpha1.HTTPPolicyBinding) (result *v1alpha1.HTTPPolicyBinding, err error) {
	result = &v1alpha1.HTTPPolicyBinding{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("httppolicybindings").
		Body(hTTPPolicyBinding).
		Do().
		Into(result)
	return
}

// Update takes the representation of a hTTPPolicyBinding and updates it. Returns the server's representation of the hTTPPolicyBinding, and an error, if there is any.
func (c *hTTPPolicyBindings) Update(hTTPPolicyBinding *v1alpha1.HTTPPolicyBinding) (result *v1alpha1.HTTPPolicyBinding, err error) {
	result = &v1alpha1.HTTPPolicyBinding{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("httppolicybindings").
		Name(hTTPPolicyBinding.Name).
		Body(hTTPPolicyBinding).
		Do().
		Into(result)
	return
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().

func (c *hTTPPolicyBindings) UpdateStatus(hTTPPolicyBinding *v1alpha1.HTTPPolicyBinding) (result *v1alpha1.HTTPPolicyBinding, err error) {
	result = &v1alpha1.HTTPPolicyBinding{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("httppolicybindings").
		Name(hTTPPolicyBinding.Name).
		SubResource("status").
		Body(hTTPPolicyBinding).
		Do().
		Into(result)
	return
}

// Delete takes name of the hTTPPolicyBinding and deletes it. Returns an error if one occurs.
func (c *hTTPPolicyBindings) Delete(name string, options *v1.DeleteOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("httppolicybindings").
		Name(name).
		Body(options).
		Do().
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *hTTPPolicyBindings) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	var timeout time.Duration
	if listOptions.TimeoutSeconds != nil {
		timeout = time.Duration(*listOptions.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Namespace(c.ns).
		Resource("httppolicybindings").
		VersionedParams(&listOptions, scheme.ParameterCodec).
		Timeout(timeout).
		Body(options).
		Do().
		Error()
}

// Patch applies the patch and returns the patched hTTPPolicyBinding.
func (c *hTTPPolicyBindings) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha1.HTTPPolicyBinding, err error) {
	result = &v1alpha1.HTTPPolicyBinding{}
	err = c.client.Patch(pt).
		Namespace(c.ns).
		Resource("httppolicybindings").
		SubResource(subresources...).
		Name(name).
		Body(data).
		Do().
		Into(result)
	return
}
