/*
Copyright 2019 Google LLC

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1alpha1 "github.com/google/knative-gcp/pkg/apis/events/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakePubSubs implements PubSubInterface
type FakePubSubs struct {
	Fake *FakeEventsV1alpha1
	ns   string
}

var pubsubsResource = schema.GroupVersionResource{Group: "events.cloud.google.com", Version: "v1alpha1", Resource: "pubsubs"}

var pubsubsKind = schema.GroupVersionKind{Group: "events.cloud.google.com", Version: "v1alpha1", Kind: "PubSub"}

// Get takes name of the pubSub, and returns the corresponding pubSub object, and an error if there is any.
func (c *FakePubSubs) Get(name string, options v1.GetOptions) (result *v1alpha1.PubSub, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(pubsubsResource, c.ns, name), &v1alpha1.PubSub{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.PubSub), err
}

// List takes label and field selectors, and returns the list of PubSubs that match those selectors.
func (c *FakePubSubs) List(opts v1.ListOptions) (result *v1alpha1.PubSubList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(pubsubsResource, pubsubsKind, c.ns, opts), &v1alpha1.PubSubList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.PubSubList{ListMeta: obj.(*v1alpha1.PubSubList).ListMeta}
	for _, item := range obj.(*v1alpha1.PubSubList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested pubSubs.
func (c *FakePubSubs) Watch(opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(pubsubsResource, c.ns, opts))

}

// Create takes the representation of a pubSub and creates it.  Returns the server's representation of the pubSub, and an error, if there is any.
func (c *FakePubSubs) Create(pubSub *v1alpha1.PubSub) (result *v1alpha1.PubSub, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(pubsubsResource, c.ns, pubSub), &v1alpha1.PubSub{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.PubSub), err
}

// Update takes the representation of a pubSub and updates it. Returns the server's representation of the pubSub, and an error, if there is any.
func (c *FakePubSubs) Update(pubSub *v1alpha1.PubSub) (result *v1alpha1.PubSub, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(pubsubsResource, c.ns, pubSub), &v1alpha1.PubSub{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.PubSub), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakePubSubs) UpdateStatus(pubSub *v1alpha1.PubSub) (*v1alpha1.PubSub, error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceAction(pubsubsResource, "status", c.ns, pubSub), &v1alpha1.PubSub{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.PubSub), err
}

// Delete takes name of the pubSub and deletes it. Returns an error if one occurs.
func (c *FakePubSubs) Delete(name string, options *v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(pubsubsResource, c.ns, name), &v1alpha1.PubSub{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakePubSubs) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(pubsubsResource, c.ns, listOptions)

	_, err := c.Fake.Invokes(action, &v1alpha1.PubSubList{})
	return err
}

// Patch applies the patch and returns the patched pubSub.
func (c *FakePubSubs) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha1.PubSub, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(pubsubsResource, c.ns, name, pt, data, subresources...), &v1alpha1.PubSub{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.PubSub), err
}
