/*
Copyright 2019 Google LLC

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1alpha1 "github.com/GoogleCloudPlatform/cloud-run-events/pkg/apis/events/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakePubSubChannels implements PubSubChannelInterface
type FakePubSubChannels struct {
	Fake *FakeEventsV1alpha1
	ns   string
}

var pubsubchannelsResource = schema.GroupVersionResource{Group: "events.cloud.run", Version: "v1alpha1", Resource: "pubsubchannels"}

var pubsubchannelsKind = schema.GroupVersionKind{Group: "events.cloud.run", Version: "v1alpha1", Kind: "PubSubChannel"}

// Get takes name of the pubSubChannel, and returns the corresponding pubSubChannel object, and an error if there is any.
func (c *FakePubSubChannels) Get(name string, options v1.GetOptions) (result *v1alpha1.PubSubChannel, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(pubsubchannelsResource, c.ns, name), &v1alpha1.PubSubChannel{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.PubSubChannel), err
}

// List takes label and field selectors, and returns the list of PubSubChannels that match those selectors.
func (c *FakePubSubChannels) List(opts v1.ListOptions) (result *v1alpha1.PubSubChannelList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(pubsubchannelsResource, pubsubchannelsKind, c.ns, opts), &v1alpha1.PubSubChannelList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.PubSubChannelList{ListMeta: obj.(*v1alpha1.PubSubChannelList).ListMeta}
	for _, item := range obj.(*v1alpha1.PubSubChannelList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested pubSubChannels.
func (c *FakePubSubChannels) Watch(opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(pubsubchannelsResource, c.ns, opts))

}

// Create takes the representation of a pubSubChannel and creates it.  Returns the server's representation of the pubSubChannel, and an error, if there is any.
func (c *FakePubSubChannels) Create(pubSubChannel *v1alpha1.PubSubChannel) (result *v1alpha1.PubSubChannel, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(pubsubchannelsResource, c.ns, pubSubChannel), &v1alpha1.PubSubChannel{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.PubSubChannel), err
}

// Update takes the representation of a pubSubChannel and updates it. Returns the server's representation of the pubSubChannel, and an error, if there is any.
func (c *FakePubSubChannels) Update(pubSubChannel *v1alpha1.PubSubChannel) (result *v1alpha1.PubSubChannel, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(pubsubchannelsResource, c.ns, pubSubChannel), &v1alpha1.PubSubChannel{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.PubSubChannel), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakePubSubChannels) UpdateStatus(pubSubChannel *v1alpha1.PubSubChannel) (*v1alpha1.PubSubChannel, error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceAction(pubsubchannelsResource, "status", c.ns, pubSubChannel), &v1alpha1.PubSubChannel{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.PubSubChannel), err
}

// Delete takes name of the pubSubChannel and deletes it. Returns an error if one occurs.
func (c *FakePubSubChannels) Delete(name string, options *v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(pubsubchannelsResource, c.ns, name), &v1alpha1.PubSubChannel{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakePubSubChannels) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(pubsubchannelsResource, c.ns, listOptions)

	_, err := c.Fake.Invokes(action, &v1alpha1.PubSubChannelList{})
	return err
}

// Patch applies the patch and returns the patched pubSubChannel.
func (c *FakePubSubChannels) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha1.PubSubChannel, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(pubsubchannelsResource, c.ns, name, data, subresources...), &v1alpha1.PubSubChannel{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.PubSubChannel), err
}
