/*
Copyright 2019 Google LLC

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1alpha1 "github.com/google/knative-gcp/pkg/apis/events/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeGCSs implements GCSInterface
type FakeGCSs struct {
	Fake *FakeEventsV1alpha1
	ns   string
}

var gcssResource = schema.GroupVersionResource{Group: "events.cloud.run", Version: "v1alpha1", Resource: "gcss"}

var gcssKind = schema.GroupVersionKind{Group: "events.cloud.run", Version: "v1alpha1", Kind: "GCS"}

// Get takes name of the gCS, and returns the corresponding gCS object, and an error if there is any.
func (c *FakeGCSs) Get(name string, options v1.GetOptions) (result *v1alpha1.GCS, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(gcssResource, c.ns, name), &v1alpha1.GCS{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.GCS), err
}

// List takes label and field selectors, and returns the list of GCSs that match those selectors.
func (c *FakeGCSs) List(opts v1.ListOptions) (result *v1alpha1.GCSList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(gcssResource, gcssKind, c.ns, opts), &v1alpha1.GCSList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.GCSList{ListMeta: obj.(*v1alpha1.GCSList).ListMeta}
	for _, item := range obj.(*v1alpha1.GCSList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested gCSs.
func (c *FakeGCSs) Watch(opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(gcssResource, c.ns, opts))

}

// Create takes the representation of a gCS and creates it.  Returns the server's representation of the gCS, and an error, if there is any.
func (c *FakeGCSs) Create(gCS *v1alpha1.GCS) (result *v1alpha1.GCS, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(gcssResource, c.ns, gCS), &v1alpha1.GCS{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.GCS), err
}

// Update takes the representation of a gCS and updates it. Returns the server's representation of the gCS, and an error, if there is any.
func (c *FakeGCSs) Update(gCS *v1alpha1.GCS) (result *v1alpha1.GCS, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(gcssResource, c.ns, gCS), &v1alpha1.GCS{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.GCS), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeGCSs) UpdateStatus(gCS *v1alpha1.GCS) (*v1alpha1.GCS, error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceAction(gcssResource, "status", c.ns, gCS), &v1alpha1.GCS{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.GCS), err
}

// Delete takes name of the gCS and deletes it. Returns an error if one occurs.
func (c *FakeGCSs) Delete(name string, options *v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(gcssResource, c.ns, name), &v1alpha1.GCS{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeGCSs) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(gcssResource, c.ns, listOptions)

	_, err := c.Fake.Invokes(action, &v1alpha1.GCSList{})
	return err
}

// Patch applies the patch and returns the patched gCS.
func (c *FakeGCSs) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha1.GCS, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(gcssResource, c.ns, name, data, subresources...), &v1alpha1.GCS{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.GCS), err
}
