/*
Copyright 2020 Google LLC

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1alpha1 "github.com/google/knative-gcp/pkg/apis/policy/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeHTTPPolicies implements HTTPPolicyInterface
type FakeHTTPPolicies struct {
	Fake *FakePolicyV1alpha1
	ns   string
}

var httppoliciesResource = schema.GroupVersionResource{Group: "policy.run.cloud.google.com", Version: "v1alpha1", Resource: "httppolicies"}

var httppoliciesKind = schema.GroupVersionKind{Group: "policy.run.cloud.google.com", Version: "v1alpha1", Kind: "HTTPPolicy"}

// Get takes name of the hTTPPolicy, and returns the corresponding hTTPPolicy object, and an error if there is any.
func (c *FakeHTTPPolicies) Get(name string, options v1.GetOptions) (result *v1alpha1.HTTPPolicy, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(httppoliciesResource, c.ns, name), &v1alpha1.HTTPPolicy{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.HTTPPolicy), err
}

// List takes label and field selectors, and returns the list of HTTPPolicies that match those selectors.
func (c *FakeHTTPPolicies) List(opts v1.ListOptions) (result *v1alpha1.HTTPPolicyList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(httppoliciesResource, httppoliciesKind, c.ns, opts), &v1alpha1.HTTPPolicyList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.HTTPPolicyList{ListMeta: obj.(*v1alpha1.HTTPPolicyList).ListMeta}
	for _, item := range obj.(*v1alpha1.HTTPPolicyList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested hTTPPolicies.
func (c *FakeHTTPPolicies) Watch(opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(httppoliciesResource, c.ns, opts))

}

// Create takes the representation of a hTTPPolicy and creates it.  Returns the server's representation of the hTTPPolicy, and an error, if there is any.
func (c *FakeHTTPPolicies) Create(hTTPPolicy *v1alpha1.HTTPPolicy) (result *v1alpha1.HTTPPolicy, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(httppoliciesResource, c.ns, hTTPPolicy), &v1alpha1.HTTPPolicy{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.HTTPPolicy), err
}

// Update takes the representation of a hTTPPolicy and updates it. Returns the server's representation of the hTTPPolicy, and an error, if there is any.
func (c *FakeHTTPPolicies) Update(hTTPPolicy *v1alpha1.HTTPPolicy) (result *v1alpha1.HTTPPolicy, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(httppoliciesResource, c.ns, hTTPPolicy), &v1alpha1.HTTPPolicy{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.HTTPPolicy), err
}

// Delete takes name of the hTTPPolicy and deletes it. Returns an error if one occurs.
func (c *FakeHTTPPolicies) Delete(name string, options *v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(httppoliciesResource, c.ns, name), &v1alpha1.HTTPPolicy{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeHTTPPolicies) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(httppoliciesResource, c.ns, listOptions)

	_, err := c.Fake.Invokes(action, &v1alpha1.HTTPPolicyList{})
	return err
}

// Patch applies the patch and returns the patched hTTPPolicy.
func (c *FakeHTTPPolicies) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha1.HTTPPolicy, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(httppoliciesResource, c.ns, name, pt, data, subresources...), &v1alpha1.HTTPPolicy{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.HTTPPolicy), err
}
