/*
Copyright 2020 Google LLC

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1alpha1 "github.com/google/knative-gcp/pkg/apis/policy/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeEventPolicies implements EventPolicyInterface
type FakeEventPolicies struct {
	Fake *FakePolicyV1alpha1
	ns   string
}

var eventpoliciesResource = schema.GroupVersionResource{Group: "policy.run.cloud.google.com", Version: "v1alpha1", Resource: "eventpolicies"}

var eventpoliciesKind = schema.GroupVersionKind{Group: "policy.run.cloud.google.com", Version: "v1alpha1", Kind: "EventPolicy"}

// Get takes name of the eventPolicy, and returns the corresponding eventPolicy object, and an error if there is any.
func (c *FakeEventPolicies) Get(name string, options v1.GetOptions) (result *v1alpha1.EventPolicy, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(eventpoliciesResource, c.ns, name), &v1alpha1.EventPolicy{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.EventPolicy), err
}

// List takes label and field selectors, and returns the list of EventPolicies that match those selectors.
func (c *FakeEventPolicies) List(opts v1.ListOptions) (result *v1alpha1.EventPolicyList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(eventpoliciesResource, eventpoliciesKind, c.ns, opts), &v1alpha1.EventPolicyList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.EventPolicyList{ListMeta: obj.(*v1alpha1.EventPolicyList).ListMeta}
	for _, item := range obj.(*v1alpha1.EventPolicyList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested eventPolicies.
func (c *FakeEventPolicies) Watch(opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(eventpoliciesResource, c.ns, opts))

}

// Create takes the representation of a eventPolicy and creates it.  Returns the server's representation of the eventPolicy, and an error, if there is any.
func (c *FakeEventPolicies) Create(eventPolicy *v1alpha1.EventPolicy) (result *v1alpha1.EventPolicy, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(eventpoliciesResource, c.ns, eventPolicy), &v1alpha1.EventPolicy{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.EventPolicy), err
}

// Update takes the representation of a eventPolicy and updates it. Returns the server's representation of the eventPolicy, and an error, if there is any.
func (c *FakeEventPolicies) Update(eventPolicy *v1alpha1.EventPolicy) (result *v1alpha1.EventPolicy, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(eventpoliciesResource, c.ns, eventPolicy), &v1alpha1.EventPolicy{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.EventPolicy), err
}

// Delete takes name of the eventPolicy and deletes it. Returns an error if one occurs.
func (c *FakeEventPolicies) Delete(name string, options *v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(eventpoliciesResource, c.ns, name), &v1alpha1.EventPolicy{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeEventPolicies) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(eventpoliciesResource, c.ns, listOptions)

	_, err := c.Fake.Invokes(action, &v1alpha1.EventPolicyList{})
	return err
}

// Patch applies the patch and returns the patched eventPolicy.
func (c *FakeEventPolicies) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha1.EventPolicy, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(eventpoliciesResource, c.ns, name, pt, data, subresources...), &v1alpha1.EventPolicy{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.EventPolicy), err
}
