// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0
// 	protoc        v3.8.0
// source: pkg/broker/control/control.proto

package control

import (
	proto "github.com/golang/protobuf/proto"
	config "github.com/google/knative-gcp/pkg/broker/config"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type WatchBrokersReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	BrokercellName      string `protobuf:"bytes,1,opt,name=brokercellName,proto3" json:"brokercellName,omitempty"`
	BrokercellNamespace string `protobuf:"bytes,2,opt,name=brokercellNamespace,proto3" json:"brokercellNamespace,omitempty"`
}

func (x *WatchBrokersReq) Reset() {
	*x = WatchBrokersReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_broker_control_control_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *WatchBrokersReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WatchBrokersReq) ProtoMessage() {}

func (x *WatchBrokersReq) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_broker_control_control_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WatchBrokersReq.ProtoReflect.Descriptor instead.
func (*WatchBrokersReq) Descriptor() ([]byte, []int) {
	return file_pkg_broker_control_control_proto_rawDescGZIP(), []int{0}
}

func (x *WatchBrokersReq) GetBrokercellName() string {
	if x != nil {
		return x.BrokercellName
	}
	return ""
}

func (x *WatchBrokersReq) GetBrokercellNamespace() string {
	if x != nil {
		return x.BrokercellNamespace
	}
	return ""
}

type BrokerUpdate struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name   *config.BrokerName   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Config *config.BrokerConfig `protobuf:"bytes,2,opt,name=config,proto3" json:"config,omitempty"`
}

func (x *BrokerUpdate) Reset() {
	*x = BrokerUpdate{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_broker_control_control_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BrokerUpdate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BrokerUpdate) ProtoMessage() {}

func (x *BrokerUpdate) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_broker_control_control_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BrokerUpdate.ProtoReflect.Descriptor instead.
func (*BrokerUpdate) Descriptor() ([]byte, []int) {
	return file_pkg_broker_control_control_proto_rawDescGZIP(), []int{1}
}

func (x *BrokerUpdate) GetName() *config.BrokerName {
	if x != nil {
		return x.Name
	}
	return nil
}

func (x *BrokerUpdate) GetConfig() *config.BrokerConfig {
	if x != nil {
		return x.Config
	}
	return nil
}

type WatchBrokersResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Updates []*BrokerUpdate `protobuf:"bytes,1,rep,name=updates,proto3" json:"updates,omitempty"`
}

func (x *WatchBrokersResp) Reset() {
	*x = WatchBrokersResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_broker_control_control_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *WatchBrokersResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WatchBrokersResp) ProtoMessage() {}

func (x *WatchBrokersResp) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_broker_control_control_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WatchBrokersResp.ProtoReflect.Descriptor instead.
func (*WatchBrokersResp) Descriptor() ([]byte, []int) {
	return file_pkg_broker_control_control_proto_rawDescGZIP(), []int{2}
}

func (x *WatchBrokersResp) GetUpdates() []*BrokerUpdate {
	if x != nil {
		return x.Updates
	}
	return nil
}

var File_pkg_broker_control_control_proto protoreflect.FileDescriptor

var file_pkg_broker_control_control_proto_rawDesc = []byte{
	0x0a, 0x20, 0x70, 0x6b, 0x67, 0x2f, 0x62, 0x72, 0x6f, 0x6b, 0x65, 0x72, 0x2f, 0x63, 0x6f, 0x6e,
	0x74, 0x72, 0x6f, 0x6c, 0x2f, 0x63, 0x6f, 0x6e, 0x74, 0x72, 0x6f, 0x6c, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x12, 0x07, 0x63, 0x6f, 0x6e, 0x74, 0x72, 0x6f, 0x6c, 0x1a, 0x1f, 0x70, 0x6b, 0x67,
	0x2f, 0x62, 0x72, 0x6f, 0x6b, 0x65, 0x72, 0x2f, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x2f, 0x74,
	0x61, 0x72, 0x67, 0x65, 0x74, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x6b, 0x0a, 0x0f,
	0x57, 0x61, 0x74, 0x63, 0x68, 0x42, 0x72, 0x6f, 0x6b, 0x65, 0x72, 0x73, 0x52, 0x65, 0x71, 0x12,
	0x26, 0x0a, 0x0e, 0x62, 0x72, 0x6f, 0x6b, 0x65, 0x72, 0x63, 0x65, 0x6c, 0x6c, 0x4e, 0x61, 0x6d,
	0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0e, 0x62, 0x72, 0x6f, 0x6b, 0x65, 0x72, 0x63,
	0x65, 0x6c, 0x6c, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x30, 0x0a, 0x13, 0x62, 0x72, 0x6f, 0x6b, 0x65,
	0x72, 0x63, 0x65, 0x6c, 0x6c, 0x4e, 0x61, 0x6d, 0x65, 0x73, 0x70, 0x61, 0x63, 0x65, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x13, 0x62, 0x72, 0x6f, 0x6b, 0x65, 0x72, 0x63, 0x65, 0x6c, 0x6c,
	0x4e, 0x61, 0x6d, 0x65, 0x73, 0x70, 0x61, 0x63, 0x65, 0x22, 0x64, 0x0a, 0x0c, 0x42, 0x72, 0x6f,
	0x6b, 0x65, 0x72, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x12, 0x26, 0x0a, 0x04, 0x6e, 0x61, 0x6d,
	0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x12, 0x2e, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67,
	0x2e, 0x42, 0x72, 0x6f, 0x6b, 0x65, 0x72, 0x4e, 0x61, 0x6d, 0x65, 0x52, 0x04, 0x6e, 0x61, 0x6d,
	0x65, 0x12, 0x2c, 0x0a, 0x06, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x14, 0x2e, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x2e, 0x42, 0x72, 0x6f, 0x6b, 0x65,
	0x72, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x52, 0x06, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x22,
	0x43, 0x0a, 0x10, 0x57, 0x61, 0x74, 0x63, 0x68, 0x42, 0x72, 0x6f, 0x6b, 0x65, 0x72, 0x73, 0x52,
	0x65, 0x73, 0x70, 0x12, 0x2f, 0x0a, 0x07, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x73, 0x18, 0x01,
	0x20, 0x03, 0x28, 0x0b, 0x32, 0x15, 0x2e, 0x63, 0x6f, 0x6e, 0x74, 0x72, 0x6f, 0x6c, 0x2e, 0x42,
	0x72, 0x6f, 0x6b, 0x65, 0x72, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x52, 0x07, 0x75, 0x70, 0x64,
	0x61, 0x74, 0x65, 0x73, 0x32, 0x56, 0x0a, 0x0d, 0x42, 0x72, 0x6f, 0x6b, 0x65, 0x72, 0x43, 0x6f,
	0x6e, 0x74, 0x72, 0x6f, 0x6c, 0x12, 0x45, 0x0a, 0x0c, 0x57, 0x61, 0x74, 0x63, 0x68, 0x42, 0x72,
	0x6f, 0x6b, 0x65, 0x72, 0x73, 0x12, 0x18, 0x2e, 0x63, 0x6f, 0x6e, 0x74, 0x72, 0x6f, 0x6c, 0x2e,
	0x57, 0x61, 0x74, 0x63, 0x68, 0x42, 0x72, 0x6f, 0x6b, 0x65, 0x72, 0x73, 0x52, 0x65, 0x71, 0x1a,
	0x19, 0x2e, 0x63, 0x6f, 0x6e, 0x74, 0x72, 0x6f, 0x6c, 0x2e, 0x57, 0x61, 0x74, 0x63, 0x68, 0x42,
	0x72, 0x6f, 0x6b, 0x65, 0x72, 0x73, 0x52, 0x65, 0x73, 0x70, 0x30, 0x01, 0x42, 0x32, 0x5a, 0x30,
	0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x67, 0x6f, 0x6f, 0x67, 0x6c,
	0x65, 0x2f, 0x6b, 0x6e, 0x61, 0x74, 0x69, 0x76, 0x65, 0x2d, 0x67, 0x63, 0x70, 0x2f, 0x70, 0x6b,
	0x67, 0x2f, 0x62, 0x72, 0x6f, 0x6b, 0x65, 0x72, 0x2f, 0x63, 0x6f, 0x6e, 0x74, 0x72, 0x6f, 0x6c,
	0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_pkg_broker_control_control_proto_rawDescOnce sync.Once
	file_pkg_broker_control_control_proto_rawDescData = file_pkg_broker_control_control_proto_rawDesc
)

func file_pkg_broker_control_control_proto_rawDescGZIP() []byte {
	file_pkg_broker_control_control_proto_rawDescOnce.Do(func() {
		file_pkg_broker_control_control_proto_rawDescData = protoimpl.X.CompressGZIP(file_pkg_broker_control_control_proto_rawDescData)
	})
	return file_pkg_broker_control_control_proto_rawDescData
}

var file_pkg_broker_control_control_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_pkg_broker_control_control_proto_goTypes = []interface{}{
	(*WatchBrokersReq)(nil),     // 0: control.WatchBrokersReq
	(*BrokerUpdate)(nil),        // 1: control.BrokerUpdate
	(*WatchBrokersResp)(nil),    // 2: control.WatchBrokersResp
	(*config.BrokerName)(nil),   // 3: config.BrokerName
	(*config.BrokerConfig)(nil), // 4: config.BrokerConfig
}
var file_pkg_broker_control_control_proto_depIdxs = []int32{
	3, // 0: control.BrokerUpdate.name:type_name -> config.BrokerName
	4, // 1: control.BrokerUpdate.config:type_name -> config.BrokerConfig
	1, // 2: control.WatchBrokersResp.updates:type_name -> control.BrokerUpdate
	0, // 3: control.BrokerControl.WatchBrokers:input_type -> control.WatchBrokersReq
	2, // 4: control.BrokerControl.WatchBrokers:output_type -> control.WatchBrokersResp
	4, // [4:5] is the sub-list for method output_type
	3, // [3:4] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_pkg_broker_control_control_proto_init() }
func file_pkg_broker_control_control_proto_init() {
	if File_pkg_broker_control_control_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_pkg_broker_control_control_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*WatchBrokersReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_broker_control_control_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BrokerUpdate); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_broker_control_control_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*WatchBrokersResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_pkg_broker_control_control_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pkg_broker_control_control_proto_goTypes,
		DependencyIndexes: file_pkg_broker_control_control_proto_depIdxs,
		MessageInfos:      file_pkg_broker_control_control_proto_msgTypes,
	}.Build()
	File_pkg_broker_control_control_proto = out.File
	file_pkg_broker_control_control_proto_rawDesc = nil
	file_pkg_broker_control_control_proto_goTypes = nil
	file_pkg_broker_control_control_proto_depIdxs = nil
}
