/*
Copyright 2020 Google LLC

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	inteventsv1 "github.com/google/knative-gcp/pkg/apis/intevents/v1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakePullSubscriptions implements PullSubscriptionInterface
type FakePullSubscriptions struct {
	Fake *FakeInternalV1
	ns   string
}

var pullsubscriptionsResource = schema.GroupVersionResource{Group: "internal.events.cloud.google.com", Version: "v1", Resource: "pullsubscriptions"}

var pullsubscriptionsKind = schema.GroupVersionKind{Group: "internal.events.cloud.google.com", Version: "v1", Kind: "PullSubscription"}

// Get takes name of the pullSubscription, and returns the corresponding pullSubscription object, and an error if there is any.
func (c *FakePullSubscriptions) Get(ctx context.Context, name string, options v1.GetOptions) (result *inteventsv1.PullSubscription, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(pullsubscriptionsResource, c.ns, name), &inteventsv1.PullSubscription{})

	if obj == nil {
		return nil, err
	}
	return obj.(*inteventsv1.PullSubscription), err
}

// List takes label and field selectors, and returns the list of PullSubscriptions that match those selectors.
func (c *FakePullSubscriptions) List(ctx context.Context, opts v1.ListOptions) (result *inteventsv1.PullSubscriptionList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(pullsubscriptionsResource, pullsubscriptionsKind, c.ns, opts), &inteventsv1.PullSubscriptionList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &inteventsv1.PullSubscriptionList{ListMeta: obj.(*inteventsv1.PullSubscriptionList).ListMeta}
	for _, item := range obj.(*inteventsv1.PullSubscriptionList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested pullSubscriptions.
func (c *FakePullSubscriptions) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(pullsubscriptionsResource, c.ns, opts))

}

// Create takes the representation of a pullSubscription and creates it.  Returns the server's representation of the pullSubscription, and an error, if there is any.
func (c *FakePullSubscriptions) Create(ctx context.Context, pullSubscription *inteventsv1.PullSubscription, opts v1.CreateOptions) (result *inteventsv1.PullSubscription, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(pullsubscriptionsResource, c.ns, pullSubscription), &inteventsv1.PullSubscription{})

	if obj == nil {
		return nil, err
	}
	return obj.(*inteventsv1.PullSubscription), err
}

// Update takes the representation of a pullSubscription and updates it. Returns the server's representation of the pullSubscription, and an error, if there is any.
func (c *FakePullSubscriptions) Update(ctx context.Context, pullSubscription *inteventsv1.PullSubscription, opts v1.UpdateOptions) (result *inteventsv1.PullSubscription, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(pullsubscriptionsResource, c.ns, pullSubscription), &inteventsv1.PullSubscription{})

	if obj == nil {
		return nil, err
	}
	return obj.(*inteventsv1.PullSubscription), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakePullSubscriptions) UpdateStatus(ctx context.Context, pullSubscription *inteventsv1.PullSubscription, opts v1.UpdateOptions) (*inteventsv1.PullSubscription, error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceAction(pullsubscriptionsResource, "status", c.ns, pullSubscription), &inteventsv1.PullSubscription{})

	if obj == nil {
		return nil, err
	}
	return obj.(*inteventsv1.PullSubscription), err
}

// Delete takes name of the pullSubscription and deletes it. Returns an error if one occurs.
func (c *FakePullSubscriptions) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(pullsubscriptionsResource, c.ns, name), &inteventsv1.PullSubscription{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakePullSubscriptions) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(pullsubscriptionsResource, c.ns, listOpts)

	_, err := c.Fake.Invokes(action, &inteventsv1.PullSubscriptionList{})
	return err
}

// Patch applies the patch and returns the patched pullSubscription.
func (c *FakePullSubscriptions) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *inteventsv1.PullSubscription, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(pullsubscriptionsResource, c.ns, name, pt, data, subresources...), &inteventsv1.PullSubscription{})

	if obj == nil {
		return nil, err
	}
	return obj.(*inteventsv1.PullSubscription), err
}
