/*
Copyright 2020 Google LLC

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	inteventsv1 "github.com/google/knative-gcp/pkg/apis/intevents/v1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeTopics implements TopicInterface
type FakeTopics struct {
	Fake *FakeInternalV1
	ns   string
}

var topicsResource = schema.GroupVersionResource{Group: "internal.events.cloud.google.com", Version: "v1", Resource: "topics"}

var topicsKind = schema.GroupVersionKind{Group: "internal.events.cloud.google.com", Version: "v1", Kind: "Topic"}

// Get takes name of the topic, and returns the corresponding topic object, and an error if there is any.
func (c *FakeTopics) Get(ctx context.Context, name string, options v1.GetOptions) (result *inteventsv1.Topic, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(topicsResource, c.ns, name), &inteventsv1.Topic{})

	if obj == nil {
		return nil, err
	}
	return obj.(*inteventsv1.Topic), err
}

// List takes label and field selectors, and returns the list of Topics that match those selectors.
func (c *FakeTopics) List(ctx context.Context, opts v1.ListOptions) (result *inteventsv1.TopicList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(topicsResource, topicsKind, c.ns, opts), &inteventsv1.TopicList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &inteventsv1.TopicList{ListMeta: obj.(*inteventsv1.TopicList).ListMeta}
	for _, item := range obj.(*inteventsv1.TopicList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested topics.
func (c *FakeTopics) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(topicsResource, c.ns, opts))

}

// Create takes the representation of a topic and creates it.  Returns the server's representation of the topic, and an error, if there is any.
func (c *FakeTopics) Create(ctx context.Context, topic *inteventsv1.Topic, opts v1.CreateOptions) (result *inteventsv1.Topic, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(topicsResource, c.ns, topic), &inteventsv1.Topic{})

	if obj == nil {
		return nil, err
	}
	return obj.(*inteventsv1.Topic), err
}

// Update takes the representation of a topic and updates it. Returns the server's representation of the topic, and an error, if there is any.
func (c *FakeTopics) Update(ctx context.Context, topic *inteventsv1.Topic, opts v1.UpdateOptions) (result *inteventsv1.Topic, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(topicsResource, c.ns, topic), &inteventsv1.Topic{})

	if obj == nil {
		return nil, err
	}
	return obj.(*inteventsv1.Topic), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeTopics) UpdateStatus(ctx context.Context, topic *inteventsv1.Topic, opts v1.UpdateOptions) (*inteventsv1.Topic, error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceAction(topicsResource, "status", c.ns, topic), &inteventsv1.Topic{})

	if obj == nil {
		return nil, err
	}
	return obj.(*inteventsv1.Topic), err
}

// Delete takes name of the topic and deletes it. Returns an error if one occurs.
func (c *FakeTopics) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(topicsResource, c.ns, name), &inteventsv1.Topic{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeTopics) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(topicsResource, c.ns, listOpts)

	_, err := c.Fake.Invokes(action, &inteventsv1.TopicList{})
	return err
}

// Patch applies the patch and returns the patched topic.
func (c *FakeTopics) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *inteventsv1.Topic, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(topicsResource, c.ns, name, pt, data, subresources...), &inteventsv1.Topic{})

	if obj == nil {
		return nil, err
	}
	return obj.(*inteventsv1.Topic), err
}
